<script>

(function() {
    var myApp = angular.module('hello', ['ui.router']);

    myApp.config(function($stateProvider) {
        // An array of state definitions
        var states = [
            { name: 'hello', url: '/hello', component: 'hello' },
            { name: 'about', url: '/about', component: 'about' },

            {
                name: 'people',
                url: '/people',
                component: 'people',
                resolve: {
                    people: function(PeopleService) {
                        return PeopleService.getAllPeople();
                    }
                }
            },

            {
                name: 'people.person',
                url: '/{personId}',
                component: 'person',
                resolve: {
                    person: function(people, $stateParams) {
                        return people.find(function(person) {
                            return person.id === $stateParams.personId;
                        });
                    }
                }
            }
        ];

        // Loop over the state definitions and register them
        states.forEach(function(state) {
            $stateProvider.state(state);
        });
    });


    myApp.service('PeopleService', function($http) {
    var service = {
        getAllPeople: function() {
            return $http.get('data/people.json', { cache: true }).then(function(resp) {
                return resp.data;
            });
        },

        getPerson: function(id) {
            function personMatchesParam(person) {
                return person.id === id;
            }

            return service.getAllPeople().then(function (people) {
                return people.find(personMatchesParam)
            });
        }
    }

    return service;
});

    myApp.component('person', {
        bindings: { person: '<' },
        template: '<h3>A person!</h3>' +

        '<div>Name: {{$ctrl.person.name}}</div>' +
        '<div>Id: {{$ctrl.person.id}}</div>' +
        '<div>Company: {{$ctrl.person.company}}</div>' +
        '<div>Email: {{$ctrl.person.email}}</div>' +
        '<div>Address: {{$ctrl.person.address}}</div>' +

        '<button ui-sref="people">Close</button>'
    });

    myApp.component('people', {
        bindings: { people: '<' },

        template: '<div class="flex-h">' +
        '  <div class="people">' +
        '    <h3>Some people:</h3>' +
        '    <ul>' +
        '      <li ng-repeat="person in $ctrl.people">' +
        '        <a ui-sref-active="active" ui-sref="people.person({ personId: person.id })">' +
        '          {{person.name}}' +
        '        </a>' +
        '      </li>' +
        '    </ul>' +
        '  </div>' +
        '  <ui-view></ui-view>' +
        '</div>'
    });

    myApp.component('hello', {
        template:  '<h3>{{$ctrl.greeting}} galaxy!</h3>' +
        '<button ng-click="$ctrl.toggleGreeting()">toggle greeting</button>',

        controller: function() {
            this.greeting = 'hello';

            this.toggleGreeting = function() {
                this.greeting = (this.greeting == 'hello') ? 'whats up' : 'hello'
            }
        }
    });

    myApp.component('about', function() {
        return {
            template:  '<h3>Its the UI-Router "Hello Galaxy" app!</h3>'
        };
    });

})();

</script>

<div ng-app="hello">

<div class="nav">
    <a ui-sref="hello" ui-sref-active="active">Hello</a>
    <a ui-sref="about" ui-sref-active="active">About</a>
    <a ui-sref="people" ui-sref-active="active">People</a>
</div>


<ui-view></ui-view>
</div>